services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\user\IdeaProjects\RateLimiter\localdata\mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sql8pass

  redis:
    image: redis:latest
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - redis.env
    ports:
      - "6379:6379"
    volumes:
      - C:\Users\user\IdeaProjects\RateLimiter\localdata\redis:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=rabbitpass
    ports:
      - "5672:5672"
      - "15672:15672"